# Header

menu:
  主页: https://baozhou.wang/
  所有文章: https://baozhou.wang/archives
  随笔: https://baozhou.wang/tags/随笔/
  技术: https://baozhou.wang/tags/技术/

# SubNav
subnav:
  github: "https://github.com/wbz93815"
  weibo: "https://weibo.com/wangbaozhou"
  rss: "https://baozhou.wang/atom.xml"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:wbz93815@gmail.com"
  #facebook: "#"
  #google: "#"
  twitter: "https://twitter.com/wbz93815"
  #linkedin: "#"

rss: https://baozhou.wang/atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: https://baozhou.wang/

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: https://static.baozhou.wang/img/ali_pay.jpeg
# 微信二维码图片地址
weixin: https://static.baozhou.wang/img/wechat_pay.jpeg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: 'de1f4e1c67ec74fb9b669cef948ba940'
google_analytics: 'UA-130022409-1'
favicon: /favicon.png

#你的头像url
#avatar: https://tvax2.sinaimg.cn/crop.0.0.958.958.180/9c88ebb3ly8fpbe1nxmnvj20qm0qmtab.jpg
avatar: https://static.baozhou.wang/img/logo.jpg
#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: cytvMawgM
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: true
disqus_shortname: baozhou-wang

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '领友'
  aboutme: '关于我'

friends:
  Tiki’s Blog: https://www.tikiliu.com/
  Adam’s Blog: http://xiaoshenge.github.io/

aboutme: 85后，天蝎男，来自江苏<br>毕业于 华东师范大学-计算机专业<br>就职于 上海某科技公司<br><br>爱好：航拍、钓鱼<br>擅长：iPhone7以下机型配件更换<br><br>在阳光下灿烂！<br>在风雨中坚强！<br>努力到无能为力！<br>拼搏到感动自己！
