# Site
title: Baozhou.Wang Blog
subtitle: PHP Developer
description: 从事互联网金融相关的研发工作，擅长后端类研发工作-PHP；近期学习GO。
author: Baozhou.Wang
language: zh-Hans
timezone: 
keywords: "计算机,互联网,技术,研发,工程师,程序员,开发者,攻城狮,程序猿,后端,PHP,GO"

url: https://baozhou.wang

source_dir: source
public_dir: public

theme: next

jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true








