# Site
title: John Blog
subtitle: PHP Developer
description: 从事互联网研发工作，擅长后端类研发工作-PHP；近期学习JAVA、GO。
author: John
language: en
timezone: UTC

theme: yilia

jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true
